version: "3.2"

services:
  producer:
    build:
      context: .
      dockerfile: ./Dockerfile.producer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  consumer:
    build:
      context: .
      dockerfile: ./Dockerfile.consumer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    ports:
    - 6379:6379
